config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  resources :addresses

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end

  belongs_to :category

  validates :name, :description, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :phone, presence: true

  has_one_attached :avatar

  has_many :addresses

  enum role: { user: 'user', admin: 'admin' }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      flash[:notice] = 'Endereço cadastrado com sucesso!'
      redirect_to action: :index
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update; end

  def destroy; end

  private

  def address_params
    params.require(:address).permit(:name, :street, :neighborhood, :number, :address_detail, :zipcode, :city, :state)
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!

    before_action :only_admin!

    private

    def only_admin!
      redirect_to root_path unless current_user.admin?
    end
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    before_action :set_category, only: %i[show edit update destroy]

    # GET /categories or /categories.json
    def index
      @categories = Category.all
    end

    # GET /categories/1 or /categories/1.json
    def show; end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit; end

    # POST /categories or /categories.json
    def create
      @category = Category.new(category_params)
        if @category.save
          redirect_to admin_categories_path(@category), notice: 'Categoria criada com sucesso!'
        else
          render :new, status: :unprocessable_entity
        end
    end

    # PATCH/PUT /categories/1 or /categories/1.json
    def update
      if @category.update(category_params)
        redirect_to admin_categories_path(@category), notice: 'Categoria atualizada com sucesso!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /categories/1 or /categories/1.json
    def destroy
      @category.destroy

      respond_to do |format|
        format.html { redirect_to admin_categories_path, notice: 'Categoria excluida com sucesso!' }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :position)
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < BaseController
    def index; end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :set_product, only: %i[show edit update destroy]

    def index
      @products = Product.all
    end

    def edit; end

    def new
      @product = authorize Product.new
    rescue Pundit::NotAuthorizedError
      flash[:notice] = 'Você só pode cadastrar um produto se tiver uma categoria criada'
      redirect_to action: :index
    end

    def show; end

    def create
      @product = Product.new(product_params)
        if @product.save
          redirect_to admin_products_path(@product), notice: 'Produto cadastrado com sucesso'
        else
          render :new, status: :unprocessable_entity
        end
    end

    def update
        if @product.update(product_params)
          redirect_to admin_products_path(@product), notice: 'Produto atualizado com sucesso!'
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_path, notice: 'Produto excluido com sucesso' }
      end
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :price, :publish, :image, :category_id, :promo, :promo_price)
    end

    def set_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :phone)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.map{ |product| ProductPresenter.new(product) }
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def password; end

  def update_user
    if current_user.update(user_params)
      redirect_to settings_path, notice: 'Seus dados foram atualizado com sucesso.'
    else
      render :index
    end
  end

  def update_password
    if !current_password_params[:current_password].empty? && current_user.valid_password?(current_password_params[:current_password])
      if current_user.update(password_params)
        bypass_sign_in(current_user)
        redirect_to password_settings_path, notice: 'Senha atualizada com sucesso.'
      else
        render :password
      end
    else
      redirect_to password_settings_path, notice: 'Você precisa informar sua senha atual para trocar de senha'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :avatar)
  end

  def current_password_params
    params.require(:user).permit(:current_password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?

    'profile'
  end
end

app/views/addresses/index.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'settings/menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2>Meus endereços</h2>
            <% if @addresses.any? %>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Rua</th>
                    <th scope="col">Bairro</th>
                    <th scope="col">Número</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
                <tbody>
                  <% @addresses.each do |address| %>
                    <tr>
                      <td><%= address.name %></td>
                      <td><%= address.street %></td>
                      <td><%= address.neighborhood %></td>
                      <td><%= address.number %></td>
                      <td>
                        <%= link_to 'Detalhes', address_path(address), class: 'btn btn-secondary' %>
                        <%= link_to 'Excluir', address_path(address), method: :delete, class: 'btn btn-danger' %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
              <h5>Nenhum endereço cadastrado.</h5>
            <% end %>
            <%= link_to "Novo endereço", new_address_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/addresses/new.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'settings/menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2>Novo endereço</h2>
            <%= simple_form_for @address, data: {turdo: false} do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs">
                <%= f.input :name, label: "Nome" %>
                <%= f.input :street, label: "Rua" %>
                <%= f.input :neighborhood, label: "Bairro" %>
                <%= f.input :number, label: "Numero" %>
                <%= f.input :address_detail, label: "Complemento" %>
                <%= f.input :zipcode, label: "CEP" %>
                <%= f.input :city, label: "Cidade" %>
                <%= f.input :state, label: "Estado" %>
              </div>
              <div class="form-actions mt-2">
                <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/categories/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do%>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button type="button"
        class="btn-close"
        data-bs-dismiss="modal"
        aria-label="Close"
        style="background: none; border:none">
            X
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/categories/form", category: @category %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editar categoria</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: 'admin/categories/form_modal', locals: { category: @category} %>
<% end %>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="h3 mb-4 text-gray-800">Categorias</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Posição</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.position %></td>
                <td>
                  <%= link_to "Detalhes", admin_category_path(category), class: 'btn btn-dark' %>
                  <%#=link_to "Back to categories", admin_categories_path %>
                  <%= link_to "Editar", edit_admin_category_path(category), data: { controller: "admin-modal"}, class: 'btn btn-warning' %>
                  <%= link_to "Excluir", admin_category_path(category), method: :delete, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Nova categoria", new_admin_category_path, data: { controller: "admin-modal"}, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h1 class="h3 mb-4 text-gray-800">Nova categoria</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: 'admin/categories/form_modal', locals: { category: @category} %>
<% end %>

app/views/admin/categories/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes da categoria</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/home/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
  <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>
<div class="row">
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              Earnings (Monthly)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
              Earnings (Annual)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
            </div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
              Pending Requests</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-comments fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :image %>
    <%= f.input :publish %>
    <%= f.input :promo %>
    <%= f.input :promo_price %>
    <%= f.association :category, include_blank: false %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/products/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do%>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button type="button"
        class="btn-close"
        data-bs-dismiss="modal"
        aria-label="Close"
        style="background: none; border:none">
            X
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/products/form", product: @product %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>
  <p>
    <strong>Imagem:</strong>
    <%= image_tag product.image.variant(:thumb) %>
  </p>
  <p>
    <strong>Descrição:</strong>
    <%= product.description %>
  </p>
  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>
  <p>
    <strong>Ativo:</strong>
    <%= product.publish %>
  </p>
</div>

app/views/admin/products/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editar produto</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: 'admin/products/form_modal', locals: { product: @product} %>
<% end %>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="h3 mb-4 text-gray-800">Produtos</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Ativo</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.name %></td>
                <td><%= product.description %></td>
                <td><%= product.price %></td>
                <td><%= product.publish %></td>
                <td>
                  <%= link_to "Detalhes", admin_product_path(product), class: 'btn btn-dark' %>
                  <%#=link_to "Back to categories", admin_categories_path %>
                  <%= link_to "Editar", edit_admin_product_path(product), data: { controller: "admin-modal"}, class: 'btn btn-warning' %>
                  <%= link_to "Excluir", admin_product_path(product), method: :delete, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Novo produto", new_admin_product_path, data: { controller: "admin-modal"}, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1 class="h3 mb-4 text-gray-800">Novo produto</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: 'admin/products/form_modal', locals: { product: @product} %>
<% end %>

app/views/admin/products/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes do produto</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @product %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja Luan - Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
      <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>
    </head>
    <body id="page-top">
      <div id="wrapper">
        <%= render 'layouts/admin/sidebar' %>
        <div id="content-wrapper" class="d-flex flex-column">
          <div id="content">
            <%=render 'layouts/admin/topbar'%>
            <div class="container-fluid">
              <%= yield %>
            </div>
          </div>
          <%= render 'layouts/admin/footer'%>
        </div>
      </div>
      <%= turbo_frame_tag "bootstrap_modal" %>
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
      </a>
    </body>
  </html>

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Ecommerce 2023</span>
    </div>
  </div>
</footer>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Admin</div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <a class="nav-link collapsed" href=" <%= admin_root_path %> ">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <a class="nav-link collapsed" href="<%= admin_categories_path %>" >
      <i class="fas fa-fw fa-bookmark"></i>
      <span>Categorias</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="<%= admin_products_path %>" >
      <i class="fas fa-fw fa-puzzle-piece"></i>
      <span>Produtos</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" data-method="delete" href="<%= destroy_user_session_path %>" >
      <i class="fas fa-fw fa-right-from-bracket"></i>
      <span>Sair</span>
    </a>
  </li>
  <hr class="sidebar-divider d-none d-md-block">
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bem vindo ao EcommerceShowzim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <!-- Navigation-->
    <%= render 'layouts/store/nav' %>
    <!-- Header-->
    <%= yield %>
    <!-- Footer-->
    <%= render 'layouts/store/footer' %>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<div class="alert alert-info text-center">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <%end%>
</div>

app/views/layouts/store/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Ecommerce Showzim 2023</p>
  </div>
</footer>

app/views/settings/_menu.html.erb
          <div class="card-header">
            Menu
          </div>
          <ul class="list-group list-group-flush">
            <a href="<%= settings_path %>" class="menu-item-profile">
              <li class="list-group-item">Perfil</li>
            </a>
            <a href="<%= password_settings_path %>" class="menu-item-profile">
              <li class="list-group-item">Alterar senha</li>
            </a>
            <a href="<%= addresses_path %>" class="menu-item-profile">
              <li class="list-group-item">Endereços</li>
            </a>
            <a href="#" class="menu-item-profile">
              <li class="list-group-item">Favoritos</li>
            </a>
          </ul>

app/views/settings/index.html.erb
<!-- Section-->
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2><%= current_user.name %></h2>
              <%= image_tag user_avatar_url(current_user), width: 120, heigth: 120, class: 'mb-4 rounded-circle' %>
            <%= simple_form_for current_user, url: update_user_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :avatar, label: false, hint: 'Escolha uma foto para a sua conta.', input_html: { class: 'input_image_full'} %>
              <%= f.input :name %>
              <%= f.input :email, readonly: true %>
              <%= f.input :phone, input_html: { class: 'mask-phone' } %>
              <%= f.button :submit, "Atualizar", class: 'btn btn-primary mt-4'%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/settings/password.html.erb
<!-- Section-->
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'menu' %>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2>Alterar senha</h2>
            <%= simple_form_for current_user, url: update_password_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :current_password %>
              <%= f.input :password %>
              <%= f.input :password_confirmation %>
              <%= f.button :submit, "Atualizar senha", class: 'btn btn-primary mt-4'%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>